[tool.poetry]
name = "agents-crewai"
version = "0.1.0"
description = ""
authors = ["Anil Bhatt"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
crewai = "0.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
